project: 
  type: website

website: 
  page-navigation: true
  title: "Data Analysis and Visualisation with R" 
  site-url: "https://meier-flo.github.io/aau-data-anal-viz/" 
  repo-url: "https://github.com/meier-flo/aau-data-anal-viz"
  repo-actions: [source, issue]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/) using a [NOAA template](https://github.com/nmfs-opensci/NOAA-quarto-simple/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: ""
    pinned: true
    align: center
    tools: 
      - icon: house
        href: https://meier-flo.github.io/aau-data-anal-viz/
        text: "Home"
      - icon: globe
        href: https://vbn.aau.dk/da/persons/fmeier
        text: "Florian Meier personal website"
      - icon: github
        href: https://github.com/meier-flo/aau-data-anal-viz
        text: "Github page of the courses"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/Session1.qmd
        text: 1.Part1:Collection, cleaning and transformation
      - href: content/Session2.qmd
        text: 2.Part2:Collection, cleaning and transformation
      - href: content/Session3.qmd
        text: 3.Data collection:crawling social media
      - href: content/Session4.qmd
        text: 4.Data analysis:descriptive statistics & visualisation
      - href: content/Session5.qmd
        text: 5.Data analysis:log analysis
        
format:
  html:
    code-fold: show  
    code-tools: true
    code-summary: "Show/Hide Code"
    highlight-style: monokai
    theme:
      light: [cosmo, theme.scss] 
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
